on:
  push:
    branches:
      - "master"
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build-binaries:
    strategy:
      matrix:
        profile:
          - name: chalice
            keyboard: "chalice"
          - name: planck
            keyboard: "planck/rev6_drop"
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - uses: actions/checkout@v4
      - name: requirements
        run: qmk setup -y
      - name: build
        run: |
          qmk import-keymap -kb ${{ matrix.profile.keyboard }} ${{ matrix.profile.name }}.json
          qmk compile -kb ${{ matrix.profile.keyboard }} -km jonk-${{ matrix.profile.name }} -t builds/jonk-${{ matrix.profile.name }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ matrix.profile.name }}:latest
          title: ${{ matrix.profile.name }}
          prerelease: false
          files: "build/jonk-${{ matrix.profile.name }}.bin"
